package:
  name: chemprop_solvation
  version: 0.0.2

source:
  path: ../

build:
  number: 0
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - matplotlib
    - {{ pin_compatible('numpy') }}
    - pandas
    - pytorch
    - rdkit
    - scikit-learn
    - tensorboardX
    - tqdm

test:
  imports:
    - chemprop_solvation

about:
  home: https://github.com/fhvermei/chemprop_solvation
